import type { CrawlConfig } from './types.js';

export const DEFAULT_CONFIG: CrawlConfig = {
  seedUrl: '',
  urls: [],
  sitemapUrls: [],
  mode: 'spider',
  maxDepth: 3,
  maxPages: 500,
  concurrency: 3,
  delayMs: 1000,
  delayExplicit: false,
  userAgent: 'Micelio/1.0 (+https://github.com/micelio)',
  jsRendering: false,
  outputPath: 'output.jsonl',
  outputFormat: 'jsonl',
  customHeaders: {},
  cookies: '',
  includePatterns: [],
  excludePatterns: [],
  checkExternal: false,
  customExtractions: [],
  customSearches: [],
  snippetPaths: [],
  psi: false,
  psiKey: '',
  aiPrompt: '',
  aiProvider: '',
  aiModel: '',
  aiKey: '',
  htmlReport: false,
  htmlOpen: true,
  pageWeight: false,
  gsc: false,
  gscProperty: '',
  gscDays: 90,
  gscKeyFile: '',
  gscBqDataset: '',
  ga4: false,
  ga4Property: '',
  ga4Days: 90,
  ga4KeyFile: '',
  segmentRules: [],
  dbPath: '',
  resume: false,
  proxy: '',
  ngrams: false,
  embeddings: false,
  embeddingModel: '',
  similarityThreshold: 0.85,
  linkIntelligence: false,
  liMaxSuggestions: 50,
  liNoCentrality: false,
  sitemapOut: false,
  sitemapChangefreq: '',
  sitemapPriority: '',
  crux: false,
  cruxKey: '',
  cruxFormFactor: '',
  plausible: false,
  plausibleSiteId: '',
  plausibleApiKey: '',
  plausibleDays: 30,
  plausibleHost: 'https://plausible.io',
  maxErrors: 0,
  timeoutSeconds: 0,
  allowedDomains: [],
  language: '',
  respectRobots: true,
  showBlockedInternal: false,
};

export function mergeConfig(partial: Partial<CrawlConfig>): CrawlConfig {
  const filtered: Partial<CrawlConfig> = {};
  for (const [key, value] of Object.entries(partial)) {
    if (value !== undefined) {
      (filtered as Record<string, unknown>)[key] = value;
    }
  }
  return { ...DEFAULT_CONFIG, ...filtered };
}
